# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.3 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# C++ compiler 
CXX := g++

# Standard flags for C++ 
CXXFLAGS := 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS := 

# Standard linker flags 
LDFLAGS := 

# Location and arguments of wx-config script 
WX_CONFIG := wx-config

# C++ flags to use with wxWidgets code 
WX_CXXFLAGS := `$(WX_CONFIG) --cxxflags`



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD
COUGAR_CXXFLAGS =  -Iinclude  $(WX_CXXFLAGS) $(CPPFLAGS) $(CXXFLAGS)
COUGAR_OBJECTS =  \
	cougar_cougarapp.o \
	cougar_cougarframe.o \
	cougar_cadmodel.o \
	cougar_facet.o \
	cougar_point.o \
	cougar_controlpanel.o \
	cougar_modelcanvas.o \
	cougar_paradialog.o \
	cougar_charvalidator.o

### Conditionally set variables: ###



### Targets: ###

all: cougar

install: all

uninstall: 

clean: 
	rm -f ./*.o
	rm -f ./*.d
	rm -f cougar

cougar: $(COUGAR_OBJECTS)
	$(CXX) -o $@ $(COUGAR_OBJECTS) $(LDFLAGS)  `$(WX_CONFIG) --libs gl,adv,core,base`

cougar_cougarapp.o: ./src/cougarapp.cpp
	$(CXX) -c -o $@ $(COUGAR_CXXFLAGS) $(CPPDEPS) $<

cougar_cougarframe.o: ./src/cougarframe.cpp
	$(CXX) -c -o $@ $(COUGAR_CXXFLAGS) $(CPPDEPS) $<

cougar_cadmodel.o: ./src/cadmodel.cpp
	$(CXX) -c -o $@ $(COUGAR_CXXFLAGS) $(CPPDEPS) $<

cougar_facet.o: ./src/facet.cpp
	$(CXX) -c -o $@ $(COUGAR_CXXFLAGS) $(CPPDEPS) $<

cougar_point.o: ./src/point.cpp
	$(CXX) -c -o $@ $(COUGAR_CXXFLAGS) $(CPPDEPS) $<

cougar_controlpanel.o: ./src/controlpanel.cpp
	$(CXX) -c -o $@ $(COUGAR_CXXFLAGS) $(CPPDEPS) $<

cougar_modelcanvas.o: ./src/modelcanvas.cpp
	$(CXX) -c -o $@ $(COUGAR_CXXFLAGS) $(CPPDEPS) $<

cougar_paradialog.o: ./src/paradialog.cpp
	$(CXX) -c -o $@ $(COUGAR_CXXFLAGS) $(CPPDEPS) $<

cougar_charvalidator.o: ./src/charvalidator.cpp
	$(CXX) -c -o $@ $(COUGAR_CXXFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean


# Dependencies tracking:
-include ./*.d
